#!/bin/bash

NAME=powerdns-admin
FLAVOUR=pgsql
VERSION=2018.03.18.1-arm64
DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
LOCATION=/home/pirate/docker_src/uip9av6y-dockerfiles/powerdns-admin/

docker build \
    --build-arg FLAVOUR=$FLAVOUR \
    --build-arg VERSION=$VERSION \
    --build-arg BUILD_DATE=$DATE \
    -t marcproux/$NAME:$VERSION \
    $LOCATION

